//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedEvent
    {
        public string eventID { get; set; }
        public System.DateTime currentDate { get; set; }
        public System.TimeSpan currentTime { get; set; }
        public string customerID { get; set; }
        public string customerName { get; set; }
        public System.DateTime eventDate { get; set; }
        public string eventName { get; set; }
        public string hall { get; set; }
        public string time { get; set; }
        public string themeColor { get; set; }
        public string decoTeam { get; set; }
        public string foodPckage { get; set; }
        public string note { get; set; }
        public Nullable<System.TimeSpan> eventTime { get; set; }
        public Nullable<int> noOfParticipants { get; set; }
        public Nullable<double> advance { get; set; }
    }
}
