//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendence1> attendence1 { get; set; }
        public virtual DbSet<Cleaner> Cleaners { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodCategory> FoodCategories { get; set; }
        public virtual DbSet<HeadChef> HeadChefs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Order_> Order_ { get; set; }
        public virtual DbSet<OrderFood> OrderFoods { get; set; }
        public virtual DbSet<OrderReadymadeProduct> OrderReadymadeProducts { get; set; }
        public virtual DbSet<ordersToBePrepared> ordersToBePrepareds { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
        public virtual DbSet<ReadyMadeProduct> ReadyMadeProducts { get; set; }
        public virtual DbSet<Reception> Receptions { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<StockAudit> StockAudits { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleCategory> VehicleCategories { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<Room1> Room1 { get; set; }
        public virtual DbSet<DecorationTeam> DecorationTeams { get; set; }
        public virtual DbSet<EventPackage> EventPackages { get; set; }
        public virtual DbSet<TempStaff> TempStaffs { get; set; }
        public virtual DbSet<BookedEvent> BookedEvents { get; set; }
        public virtual DbSet<expOrder> expOrders { get; set; }
        public virtual DbSet<Rent> Rents { get; set; }
        public virtual DbSet<Rent_2> Rent_2 { get; set; }
        public virtual DbSet<evPay> evPays { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    
        public virtual ObjectResult<getExpiredItems_Result> getExpiredItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExpiredItems_Result>("getExpiredItems");
        }
    
        public virtual ObjectResult<getExpiredItems1_Result> getExpiredItems1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExpiredItems1_Result>("getExpiredItems1");
        }
    
        public virtual ObjectResult<getExpiredItemsWithinNextMonth_Result> getExpiredItemsWithinNextMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExpiredItemsWithinNextMonth_Result>("getExpiredItemsWithinNextMonth");
        }
    
        public virtual ObjectResult<getOrderedItems_Result> getOrderedItems(string orderID)
        {
            var orderIDParameter = orderID != null ?
                new ObjectParameter("orderID", orderID) :
                new ObjectParameter("orderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOrderedItems_Result>("getOrderedItems", orderIDParameter);
        }
    
        public virtual ObjectResult<getExpiredReadyMades_Result> getExpiredReadyMades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExpiredReadyMades_Result>("getExpiredReadyMades");
        }
    
        public virtual ObjectResult<getExpiredReadyMadesWithinNextMonth_Result> getExpiredReadyMadesWithinNextMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExpiredReadyMadesWithinNextMonth_Result>("getExpiredReadyMadesWithinNextMonth");
        }
    
        public virtual ObjectResult<getOrderedItems1_Result> getOrderedItems1(string orderID)
        {
            var orderIDParameter = orderID != null ?
                new ObjectParameter("orderID", orderID) :
                new ObjectParameter("orderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOrderedItems1_Result>("getOrderedItems1", orderIDParameter);
        }
    
        public virtual ObjectResult<attenSummery_Result> attenSummery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<attenSummery_Result>("attenSummery");
        }
    
        public virtual ObjectResult<searchItem_Result> searchItem(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchItem_Result>("searchItem", keywordParameter);
        }
    
        public virtual ObjectResult<getSearchFood_Result> getSearchFood(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSearchFood_Result>("getSearchFood", keywordParameter);
        }
    
        public virtual ObjectResult<getSearchItems_Result> getSearchItems(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSearchItems_Result>("getSearchItems", keywordParameter);
        }
    }
}
