//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecorationTeam
    {
        public string dtID { get; set; }
        public string dtName { get; set; }
        public int NoOfMembers { get; set; }
        public double price { get; set; }
        public int contactNo { get; set; }
        public string email { get; set; }
        public string description { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
    }
}
