//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public string driverid { get; set; }
        public string service { get; set; }
        public Nullable<int> licenceNo { get; set; }
        public string type { get; set; }
    }
}
