//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public string PaymentID { get; set; }
        public int RentID { get; set; }
        public string DriverID { get; set; }
        public string VehiID { get; set; }
        public string CusID { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime AfterDate { get; set; }
        public int NoOfKM { get; set; }
        public double TotalPrice { get; set; }
        public double Advance { get; set; }
        public double Balance { get; set; }
    }
}
