//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_2
    {
        public string RentID { get; set; }
        public string CustomerID { get; set; }
        public string vehicleID { get; set; }
        public string DriverID { get; set; }
        public string CustomerName { get; set; }
        public int phone { get; set; }
        public string type { get; set; }
        public string vehicleNo { get; set; }
        public System.DateTime RentDate { get; set; }
        public byte[] VehicleImage { get; set; }
        public Nullable<System.DateTime> AfterDate { get; set; }
    }
}
