//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room1
    {
        public string RoomID { get; set; }
        public string RoomNo { get; set; }
        public string bedtype { get; set; }
        public string maxaadult { get; set; }
        public string floor { get; set; }
        public string roomtype { get; set; }
        public byte[] RoomImage { get; set; }
        public string available { get; set; }
    }
}
