//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAudit
    {
        public string stockAuditID { get; set; }
        public string itemID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> inOut { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
