//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCategory
    {
        public string vehicleCategoryID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual VehicleCategory VehicleCategory1 { get; set; }
        public virtual VehicleCategory VehicleCategory2 { get; set; }
    }
}
