//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string vehicleID { get; set; }
        public string vehicleNo { get; set; }
        public string type { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string InsuaranceType { get; set; }
        public Nullable<double> RentPerDay { get; set; }
        public Nullable<double> RentPerkm { get; set; }
        public byte[] VehicleImage { get; set; }
    
        public virtual Vehicle Vehicle1 { get; set; }
        public virtual Vehicle Vehicle2 { get; set; }
    }
}
